### ISSUE TITLE
[PE-D] Standardise command output for commands

### ISSUE THREAD

**Issue by nus-se-script** [AY2122S2-CS2103-W16-3/tp#145]
Test input commands:
`addgroup g/TeStinG 3` outputs `New student group added: TeStinG 3`
`delgroup g/tEsTiNg 3` outputs `Deleted group: tEsTiNg 3`

`assign 1 g/TeStiNg-1` outputs `Student Alex Yeoh [alexyeoh@u.nus.edu] assigned to testing-1`
`deassign 1 g/TeStiNg-1` outputs `Student Alex Yeoh [alexyeoh@u.nus.edu] deassigned from testing-1`

Maybe standardising the output `GROUP_NAME` or `TASK_NAME` based on the user input or the data stored in the app would be great but not both.

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: xSaints19x/ped#3

**Comment by Punpun1643** [comment]
Actually I think this suggestion is good. However, since this is a `type.FeatureFlaw` unfortunately it can't be solved.

However, I think that the severity should be `severity.VeryLow` if this were to be considered a bug as I do not see how not standardising the case would affect the **usage** in any way. I see this as a **cosmetic issue** based on this:

![Screenshot 2022-04-03 at 8 50 29 PM](https://user-images.githubusercontent.com/60144099/161428933-209c31d1-c4fd-437d-b8ce-c89db201a52e.png)
