### ISSUE TITLE
[PE-D] Viewing Student Groups

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S2-CS2103-W16-3/tp#177]
To be able to view a group, users have to type in the exact group name e.g. 

Command executed: `viewtask g/NUS Data Science Society`

![Screenshot 2022-04-01 at 4.27.10 PM.png](https://raw.githubusercontent.com/tsumian/ped/main/files/ba7ad332-e102-4d31-a1e3-8e31907fe2e9.png)

Expected behaviour: To be able to use `INDEX` of groups as discussed in FAQ part of UG to find groups instead of typing out the exact name so as to minimise typo errors

![Screenshot 2022-04-01 at 4.28.56 PM.png](https://raw.githubusercontent.com/tsumian/ped/main/files/d2472619-c28c-4fe4-bda0-b96ad22dbf52.png)

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: tsumian/ped#11

**Comment by Punpun1643** [comment]
This is not a functionality bug as users are **expected** to view tasks in a particular group via this command: `viewtask task/TASK_NAME g/GROUP_NAME`. Therefore, to be able to view a task in a group, users would need to type the group name which is a correct expected behaviour. 

At most you could argue that it is a `severity.Low` `type.FeatureFlaw` because users would need to type a group name. However, I don't think this is a problem for a **fast typist**. Moreover, to reduce the problematic way of having to type the long group name, the app is designed such that group names are **case insensitive**. This means, `NUS Fintech Society` = `nus fintech society` = `NuS FintECH soCIety`. This is to help the user to be able to refer to the correct group faster without having to worry about case sensitivity, and minimise typo error. 

As for the `INDEX` issue in the Q&A, it is just to explain what an index means. In the app, index appear in the person list and the group list, that is why it is being explained that way. Will consider removing the reference to group list.
